server:
  port: 8082
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/customer?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    username: eda
    password: 6882318Eda
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

